name: Build Umami

on:
  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, chrome]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: |
        npm ci
        npx gulp
        npx gulp ${{ matrix.browser }}
      env:
        build_name: umami-${{ matrix.browser }}.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.browser }}
        path: umami-${{ matrix.browser }}.zip